### ISSUE TITLE
Actualize AssemblyInfo.cs

### ISSUE THREAD

**Issue by tophf** [bkeiren/EasyImgur#15]
AssemblyFileVersion in [AssemblyInfo.cs](https://github.com/bkeiren/EasyImgur/blob/master/EasyImgur/Properties/AssemblyInfo.cs) could be updated with each release, as well as the copyright year. Windows Explorer and various file utilities show this in tooltips, properties and so on.

**Comment by bkeiren** [comment]
Implemented in ff03a860ad8f57b91768f779291ba43f521e9bed.
