### ISSUE TITLE
Option to copy HTTPS links

### ISSUE THREAD

**Issue by tophf** [bkeiren/EasyImgur#16]
Rationale:

* imgur.com supports `https`
* `https` is used by many sites nowadays
* embedding a non-secure `http` image makes a page non-secure, Mixed Content warning looks bad.
* manually typing `s` each time is kinda cumbersome and undermines the "Easy" part.

So, this will be very helpful for those who mostly/exclusively use `https` sites.

**Comment by cubrr** [comment]
I'm working on this.

**Comment by bkeiren** [comment]
Implemented by commit e254be3, next release will incorporate this.
