### ISSUE TITLE
annoying popup on startup

### ISSUE THREAD

**Issue by remizik** [bkeiren/EasyImgur#44]
Hi,

this is very annoying : http://i.imgur.com/ZWtfcXx.png

can you please remove it ? or at least add an option to disable it ?

awesome little tool anyway, thanks a lot !

**Comment by bkeiren** [comment]
This feature has been added in release [0.3.3](https://github.com/bkeiren/EasyImgur/releases/tag/0.3.3).

**Comment by remizik** [comment]
thanks a lot <3
