### ISSUE TITLE
Exception causing crash at start up

### ISSUE THREAD

**Issue by STaRDoGG** [bkeiren/EasyImgur#45]
Been using this app for quite a while now and it has always worked fine, but it's suddenly crashing upon start up, and showing this in the log file:

> [WARNING] Couldn't resolve assembly: 'EasyImgur.EasyImgur.resources.dll'

Any suggestions?

**Comment by cxcorp** [comment]
That's a warning which shouldn't affect the program's usage. You've probably experienced #46
