### ISSUE TITLE
Running out of memory

### ISSUE THREAD

**Issue by TheTou** [bkeiren/EasyImgur#48]
When uploading multiple Images it seems like the executable loads all files into memory at once, causing it to run out of memory at some point. Can you please optimize this behaviour, so the files will be read in sequential order to reduce RAM consumption? At the moment the program runs out of memory when using 1.5GB of RAM. I patched it with the tool from http://www.ntcore.com/4gb_patch.php but then it runs out of memory at 3.5GB, which is still a problem for large albums. Thanks!

**Comment by bkeiren** [comment]
Hey TheTou,

Thanks for reporting this, great find! I'll pick this up as soon as possible.

Cheers

**Comment by bkeiren** [comment]
Hi @TheTou, the fix for this has been included in the latest release. You can find the latest release [here](https://github.com/bkeiren/EasyImgur/releases/latest).
