### ISSUE TITLE
Copy http links instead of https (maybe a setting ?)

### ISSUE THREAD

**Issue by remizik** [bkeiren/EasyImgur#55]
Hi,

could you add a setting that remove the "s" in "https" in the auto copied links after upload ?
I'm using this app mostly to post on a forum and https links are sometimes a problem.

thanks :)
cheers

**Comment by ThiefMaster** [comment]
Linking to https should never be a problem, unless the forum is crap. Embedding secure content on an insecure site is usually fine, it's just the other way round that is problematic.

**Comment by remizik** [comment]
well, https is working fine, it's just that when someone quotes you on this forum and the image links have https instead of http, the quote has images in it instead of urls.

I realize it's very specific to me so no worries.
