### ISSUE TITLE
EasyImgur attempts to "call home" to an unknown IP address at launch

### ISSUE THREAD

**Issue by dizzy-egg** [bkeiren/EasyImgur#59]
When I launch EasyImgur it attempts to make an HTTPS request to an unknown IP address: `46.30.215.5`.

Personally I would prefer it does not make any net requests except those necessary to function.

What's it doing this for, and is there a way to turn it off, please?

**Comment by bkeiren** [comment]
Hey @dizzy-egg, 

Thanks for your request! I'm happy to report that I've just released [a new version](releases/latest/) (0.4.0 to be specific) which includes a checkbox labeled "Enable Telemetry" in the *General settings tab* of EasyImgur. Unchecking this will disable all telemetry from being sent.

Hope this helps, and thanks again!
