### ISSUE TITLE
A question about requirements.

### ISSUE THREAD

**Issue by TheBetterRed** [bkeiren/EasyImgur#6]
I'm running Windows XP (32bit) and I was wondering for EasyImgur only worked on later OSs or 64bit architectures. The reason I ask is the tool simply doesn't work for me; more so the application icon doesn't even appear.

If this isn't due to the requirements, then I guess it's a fault from my side.

(:

**Comment by tophf** [comment]
When I used XP 32bit a few years ago I had a problem with NET4 apps, so I followed the well-known procedure: uninstall all NET framework packages (e.g. [.NET Framework Cleanup Tool](http://blogs.msdn.com/b/astebner/archive/2008/08/28/8904493.aspx)), reinstall.
